// <auto-generated />
using System.Collections.Generic;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(FriendlyDbContext))]
    [Migration("20260310212253_SeedHatEligibleData")]
    partial class SeedHatEligibleData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Data.Entities.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("EligibleForHat")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = "-9998-01-01 00:00:00",
                            Name = "Acme Corp",
                            UpdatedAt = "-9998-01-01 00:00:00"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = "-9998-01-01 00:00:00",
                            Name = "Globex Inc",
                            UpdatedAt = "-9998-01-01 00:00:00"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = "-9998-01-01 00:00:00",
                            Name = "Initech",
                            UpdatedAt = "-9998-01-01 00:00:00"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = "-9998-01-01 00:00:00",
                            Name = "Umbrella Corp",
                            UpdatedAt = "-9998-01-01 00:00:00"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = "-9998-01-01 00:00:00",
                            Name = "Stark Industries",
                            UpdatedAt = "-9998-01-01 00:00:00"
                        });
                });

            modelBuilder.Entity("Data.Entities.Load", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Load");
                });

            modelBuilder.Entity("Data.Entities.Stop", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("LoadId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "AppointmentWindow", "Data.Entities.Stop.AppointmentWindow#LocalTimeWindow", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("End")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("AppointmentLocalEndTime");

                            b1.Property<string>("Start")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("AppointmentLocalStartTime");

                            b1.Property<string>("ZoneId")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("AppointmentTimeZoneId");
                        });

                    b.HasKey("Id");

                    b.HasIndex("LoadId");

                    b.ToTable("Stop");
                });

            modelBuilder.Entity("Data.Entities.Load", b =>
                {
                    b.HasOne("Data.Entities.Customer", "Customer")
                        .WithMany("Loads")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Data.Entities.Stop", b =>
                {
                    b.HasOne("Data.Entities.Load", "Load")
                        .WithMany("Stops")
                        .HasForeignKey("LoadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Load");
                });

            modelBuilder.Entity("Data.Entities.Customer", b =>
                {
                    b.Navigation("Loads");
                });

            modelBuilder.Entity("Data.Entities.Load", b =>
                {
                    b.Navigation("Stops");
                });
#pragma warning restore 612, 618
        }
    }
}
